=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak04/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="autoDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="autok" type="autokTipus"/>
        <xs:element name="tulajdonosok" type="tulajdonosokTipus"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="autoPK">
      <xs:selector xpath="autok/auto"/>
      <xs:field xpath="@rsz"/>
    </xs:key>
    
    <xs:key name="tulajdonosPK">
      <xs:selector xpath="tulajdonosok/tulajdonos"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:keyref name="tulajdonosAutoFK" refer="autoPK">
      <xs:selector xpath="tulajdonosok/tulajdonos/autok/auto"/>
      <xs:field xpath="."/>
    </xs:keyref>
  </xs:element>
  
  <xs:complexType name="autokTipus">
    <xs:sequence>
      <xs:element name="auto" type="autoTipus" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="tulajdonosokTipus">
    <xs:sequence>
      <xs:element name="tulajdonos" type="tulajdonosTipus" maxOccurs="unbounded">
        <xs:unique name="tulajdonosAutoUnique">
          <xs:selector xpath="autok/auto"/>
          <xs:field xpath="."/>
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:simpleType name="rszTipus">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="autoTipus">
    <xs:sequence>
      <xs:element name="gyarto" type="xs:string"/>
      <xs:element name="modell" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="rsz" type="rszTipus" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="tulajdonosTipus">
    <xs:sequence>
      <xs:element name="nev" type="xs:string"/>
      <xs:element name="autok">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="auto" type="rszTipus" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>
  
</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak04_start/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<autoDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="1.xsd">
  <autok>
    <auto rsz="ABC-123">
      <gyarto>Gyártó 1</gyarto>
      <modell>Modell 1</modell>
    </auto>
    <auto rsz="ABC-124">
      <gyarto>Gyártó 2</gyarto>
      <modell>Modell 2</modell>
    </auto>
    <auto rsz="ABC-125">
      <gyarto>Gyártó 3</gyarto>
      <modell>Modell 3</modell>
    </auto>
  </autok>
  
  <tulajdonosok>
    <tulajdonos id="1">
      <nev>X1 Y1</nev>
      <autok>
        <auto>ABC-123</auto>
      </autok>
    </tulajdonos>
    <tulajdonos id="2">
      <nev>X Y2</nev>
      <autok>
        <auto>ABC-124</auto>
        <auto>ABC-125</auto>
      </autok>
    </tulajdonos>
  </tulajdonosok>
</autoDB>
