=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak02/5.dtd
<!ELEMENT email-kliens (email*)>

<!ELEMENT nev (#PCDATA)>
<!ELEMENT email-cim (#PCDATA)>
<!ELEMENT telefonszam (#PCDATA)>
<!ATTLIST telefonszam korzet CDATA #IMPLIED>
<!ENTITY % elerhetoseg "nev, email-cim, telefonszam?">

<!ELEMENT email (felado, cimzettek, datum, targy, formatum, tartalom)>
<!ATTLIST email id ID #REQUIRED>

<!ELEMENT felado (%elerhetoseg;)>

<!ELEMENT cimzettek (cimzett+)>
<!ELEMENT cimzett (%elerhetoseg;)>
<!ATTLIST cimzett tipus (cimzett | masolat | titkos-masolat) "cimzett">

<!ELEMENT datum (#PCDATA)>
<!ELEMENT targy (#PCDATA)>
<!ELEMENT formatum (#PCDATA)>
<!ELEMENT tartalom (#PCDATA)>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak02/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE email-kliens SYSTEM "5.dtd">
<email-kliens>
  <email id="e1">
    <felado>
      <nev>X1 Y1</nev>
      <email-cim>x1.y1@gmail.com</email-cim>
      <telefonszam korzet="46">123-456</telefonszam>
    </felado>
    
    <cimzettek>
      <cimzett tipus="cimzett">
        <nev>X2 Y2</nev>
        <email-cim>x2.y2@gmail.com</email-cim>
        <telefonszam korzet="46">123-456</telefonszam>
      </cimzett>
      <cimzett tipus="masolat">
        <nev>X4 Y4</nev>
        <email-cim>x4.y4@gmail.com</email-cim>
      </cimzett>
      <cimzett tipus="titkos-masolat">
        <nev>X6 Y6</nev>
        <email-cim>x6.y6@gmail.com</email-cim>
      </cimzett>
    </cimzettek>
    
    <datum>2013-09-14</datum>
    <targy>TÃ¡rgy 1</targy>
    <formatum>text/plain</formatum>
    <tartalom>
      <![CDATA[
        ...
      ]]>
    </tartalom>
  </email>
</email-kliens>
