=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak02/7.g.dtd
<!ELEMENT gyoker (egyed1-reszfa, egyed2-reszfa, kapcsolo-egyedek)>

<!ELEMENT egyed1-reszfa (egyed1*)>
<!ELEMENT egyed1 EMPTY>
<!ATTLIST egyed1 id ID #REQUIRED>

<!ELEMENT egyed2-reszfa (egyed2*)>
<!ELEMENT egyed2 EMPTY>
<!ATTLIST egyed2 id ID #REQUIRED>

<!ELEMENT kapcsolo-egyedek (kapcsolo-egyed*)>
<!ELEMENT kapcsolo-egyed EMPTY>
<!ATTLIST kapcsolo-egyed egyed1 IDREF #REQUIRED>
<!ATTLIST kapcsolo-egyed egyed2 IDREF #REQUIRED>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak02/7.g.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gyoker SYSTEM "7.g.dtd">
<gyoker>
  <egyed1-reszfa>
    <egyed1 id="x1"/>
    <egyed1 id="x2"/>
  </egyed1-reszfa>
  
  <egyed2-reszfa>
    <egyed2 id="y1"/>
    <egyed2 id="y2"/>
  </egyed2-reszfa>
  
  <kapcsolo-egyedek>
    <kapcsolo-egyed egyed1="x1" egyed2="y1"/>
    <kapcsolo-egyed egyed1="x1" egyed2="y2"/>
    <kapcsolo-egyed egyed1="x2" egyed2="y1"/>
  </kapcsolo-egyedek>
</gyoker>
