=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh2_start_a/src/data/autok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:a="http://iit.uni-miskolc.hu/xml/autok"
           targetNamespace="http://iit.uni-miskolc.hu/xml/autok"
           elementFormDefault="qualified">
  
  <xs:element name="autok">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="auto" type="a:autoTipus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="rszPK">
      <xs:selector xpath="a:auto"/>
      <xs:field xpath="@rendszam"/>
    </xs:key>
  </xs:element>
  
  <xs:complexType name="autoTipus">
    <xs:sequence>
      <xs:element name="marka" type="xs:string"/>
      <xs:element name="gyartasi-ev" type="xs:gYear"/>
      <xs:element name="szin" type="a:szinTipus" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rendszam" type="a:rendszamTipus" use="required"/>
  </xs:complexType>
  
  <xs:simpleType name="rendszamTipus">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="szinSimpleTipus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="fehér"/>
      <xs:enumeration value="ezüst"/>
      <xs:enumeration value="fekete"/>
      <xs:enumeration value="piros"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="szinTipus">
    <xs:simpleContent>
      <xs:extension base="a:szinSimpleTipus">
        <xs:attribute name="metalozott" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh2_start_a/src/data/autok.xml
<?xml version="1.0" encoding="UTF-8"?>
<a:autok xmlns:a="http://iit.uni-miskolc.hu/xml/autok"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://iit.uni-miskolc.hu/xml/autok autok.xsd">
  
  <a:auto rendszam="ABC-123">
    <a:marka>Honda</a:marka>
    <a:gyartasi-ev>2013</a:gyartasi-ev>
    <a:szin metalozott="true">fehér</a:szin>
  </a:auto>
  
  <a:auto rendszam="ABC-124">
    <a:marka>Mercedes</a:marka>
    <a:gyartasi-ev>2013</a:gyartasi-ev>
    <a:szin>ezüst</a:szin>
  </a:auto>
  
  <a:auto rendszam="ABC-125">
    <a:marka>BMW</a:marka>
    <a:gyartasi-ev>2014</a:gyartasi-ev>
    <a:szin metalozott="true">fekete</a:szin>
  </a:auto>
  
  <a:auto rendszam="ABC-126">
    <a:marka>BMW</a:marka>
    <a:gyartasi-ev>2014</a:gyartasi-ev>
  </a:auto>
  
  <a:auto rendszam="ABC-127">
    <a:marka>Ferrari</a:marka>
    <a:gyartasi-ev>2014</a:gyartasi-ev>
    <a:szin metalozott="true">piros</a:szin>
  </a:auto>
  
</a:autok>
