=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak03/2.g.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="gyoker">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="egyed1-reszfa" type="egyed1ReszfaTipus"/>
        <xs:element name="egyed2-reszfa" type="egyed2ReszfaTipus"/>
        <xs:element name="kapcsolo-egyedek" type="kapcsoloEgyedReszfaTipus"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="egyed1Kulcs">
      <xs:selector xpath="egyed1-reszfa/egyed1"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:key name="egyed2Kulcs">
      <xs:selector xpath="egyed2-reszfa/egyed2"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:keyref name="egyed1IdegenKulcs" refer="egyed1Kulcs">
      <xs:selector xpath="kapcsolo-egyedek/kapcsolo-egyed"/>
      <xs:field xpath="@egyed1"/>
    </xs:keyref>
    
    <xs:keyref name="egyed2IdegenKulcs" refer="egyed2Kulcs">
      <xs:selector xpath="kapcsolo-egyedek/kapcsolo-egyed"/>
      <xs:field xpath="@egyed2"/>
    </xs:keyref>
  </xs:element>
  
  <xs:complexType name="egyed1ReszfaTipus">
    <xs:sequence>
      <xs:element name="egyed1" type="egyed1Tipus" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="egyed2ReszfaTipus">
    <xs:sequence>
      <xs:element name="egyed2" type="egyed2Tipus" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="kapcsoloEgyedReszfaTipus">
    <xs:sequence>
      <xs:element name="kapcsolo-egyed" type="kapcsoloEgyedTipus" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="egyed1Tipus">
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="egyed2Tipus">
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="kapcsoloEgyedTipus">
    <xs:attribute name="egyed1" type="xs:int" use="required"/>
    <xs:attribute name="egyed2" type="xs:int" use="required"/>
  </xs:complexType>

</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak03/2.g.xml
<?xml version="1.0" encoding="UTF-8"?>
<gyoker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="2.g.xsd">
  <egyed1-reszfa>
    <egyed1 id="1"/>
    <egyed1 id="2"/>
  </egyed1-reszfa>
  
  <egyed2-reszfa>
    <egyed2 id="1"/>
    <egyed2 id="2"/>
  </egyed2-reszfa>
  
  <kapcsolo-egyedek>
    <kapcsolo-egyed egyed1="1" egyed2="1"/>
    <kapcsolo-egyed egyed1="1" egyed2="2"/>
    <kapcsolo-egyed egyed1="2" egyed2="1"/>
  </kapcsolo-egyedek>
</gyoker>
