=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak03/3.a.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="softwareCompany">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="developers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="developer" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name"/>
                    <xs:element name="technologies">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="technology" maxOccurs="unbounded">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="C#"/>
                                <xs:enumeration value="Java"/>
                                <xs:enumeration value="C++"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="developerID" type="xs:int" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="teams">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="team" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="members">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="member" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="developerID" type="xs:int" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="teamID" type="xs:int" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="projects">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="project" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="associatedTeams">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="associatedTeam" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="teamID" type="xs:int" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="projectID" type="xs:int" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="worklogs">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="worklog" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="meeting" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:int">
                            <xs:attribute name="projectID" type="xs:int" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:choice>
                      <xs:sequence>
                        <xs:element name="designing" minOccurs="0">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:int">
                                <xs:attribute name="projectID" type="xs:int" use="required"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="programming">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:int">
                                <xs:attribute name="projectID" type="xs:int" use="required"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:element name="testing" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:int">
                                <xs:attribute name="projectID" type="xs:int" use="required"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:sequence>
                        <xs:element name="testing">
                          <xs:complexType>
                            <xs:simpleContent>
                              <xs:extension base="xs:int">
                                <xs:attribute name="projectID" type="xs:int" use="required"/>
                              </xs:extension>
                            </xs:simpleContent>
                          </xs:complexType>
                        </xs:element>
                        <xs:choice>
                          <xs:element name="demo">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="projectID" type="xs:int" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="bugFixing">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:int">
                                  <xs:attribute name="projectID" type="xs:int" use="required"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:choice>
                      </xs:sequence>
                    </xs:choice>
                  </xs:sequence>
                  <xs:attribute name="developer" type="xs:int" use="required"/>
                  <xs:attribute name="date" type="xs:date" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/gyak03/3.a.xml
<?xml version="1.0" encoding="UTF-8"?>
<softwareCompany xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="3.a.xsd">
  <developers>
    <developer developerID="1">
      <name>X1 Y1</name>
      <technologies>
        <technology>C#</technology>
        <technology>Java</technology>
      </technologies>
    </developer>
    <developer developerID="2">
      <name>X2 Y2</name>
      <technologies>
        <technology>C++</technology>
      </technologies>
    </developer>
    <developer developerID="3">
      <name>X3 Y3</name>
      <technologies>
        <technology>Java</technology>
        <technology>C++</technology>
        <technology>C#</technology>
      </technologies>
    </developer>
    <developer developerID="4">
      <name>X4 Y4</name>
      <technologies>
        <technology>Java</technology>
      </technologies>
    </developer>
  </developers>
  
  <teams>
    <team teamID="1">
      <name>Team 1</name>
      <members>
        <member developerID="1"/>
        <member developerID="2"/>
      </members>
    </team>
    <team teamID="2">
      <name>Team 2</name>
      <members>
        <member developerID="3"/>
        <member developerID="4"/>
      </members>
    </team>
  </teams>
  
  <projects>
    <project projectID="1">
      <name>Project 1</name>
      <associatedTeams>
        <associatedTeam teamID="1"/>
        <associatedTeam teamID="2"/>
      </associatedTeams>
    </project>
    <project projectID="2">
      <name>Project 2</name>
      <associatedTeams>
        <associatedTeam teamID="2"/>
      </associatedTeams>
    </project>
  </projects>
  
  <worklogs>
    <worklog developer="1" date="2013-10-01">
      <meeting projectID="1">1</meeting>
      <meeting projectID="2">1</meeting>
      <designing projectID="1">4</designing>
      <programming projectID="1">2</programming>
    </worklog>
    <worklog developer="1" date="2013-10-02">
      <meeting projectID="1">1</meeting>
      <designing projectID="1">3</designing>
      <programming projectID="1">3</programming>
      <testing projectID="1">1</testing>
    </worklog>
    <worklog developer="1" date="2013-10-03">
      <meeting projectID="1">1</meeting>
      <designing projectID="1">2</designing>
      <programming projectID="1">3</programming>
      <testing projectID="1">1</testing>
      <testing projectID="2">1</testing>
    </worklog>
    <worklog developer="1" date="2013-10-04">
      <meeting projectID="1">1</meeting>
      <programming projectID="1">7</programming>
    </worklog>
    <worklog developer="1" date="2013-10-05">
      <meeting projectID="1">1</meeting>
      <programming projectID="1">5</programming>
      <testing projectID="1">2</testing>
    </worklog>
    <worklog developer="1" date="2013-10-06">
      <meeting projectID="1">1</meeting>
      <programming projectID="1">5</programming>
      <testing projectID="1">1</testing>
      <testing projectID="2">1</testing>
    </worklog>
    <worklog developer="1" date="2013-10-07">
      <meeting projectID="1">2</meeting>
      <testing projectID="1">3</testing>
      <demo projectID="1">3</demo>
    </worklog>
    <worklog developer="1" date="2013-10-08">
      <meeting projectID="1">1</meeting>
      <testing projectID="1">3</testing>
      <bugFixing projectID="1">4</bugFixing>
    </worklog>
  </worklogs>
</softwareCompany>
