=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh1/a.dtd
<!ELEMENT hallgatok (hallgato*)>
<!ELEMENT hallgato (nev, szuletesi-datum, telefonszam?)>
<!ELEMENT nev (#PCDATA)>
<!ELEMENT szuletesi-datum (#PCDATA)>
<!ELEMENT telefonszam (#PCDATA)>
<!ATTLIST telefonszam korzet CDATA #IMPLIED>
<!ATTLIST hallgato neptun ID #REQUIRED>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh1/a.dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hallgatok SYSTEM "a.dtd">
<hallgatok>
  
  <hallgato neptun="ABCD12">
    <nev>X1 Y1</nev>
    <szuletesi-datum>1990-01-01</szuletesi-datum>
    <telefonszam korzet="46">123-456</telefonszam>
  </hallgato>
  
  <hallgato neptun="ABCD13">
    <nev>X2 Y2</nev>
    <szuletesi-datum>1991-01-01</szuletesi-datum>
    <telefonszam>123-457</telefonszam>
  </hallgato>
  
  <hallgato neptun="ABCD14">
    <nev>X2 Y2</nev>
    <szuletesi-datum>1991-01-01</szuletesi-datum>
  </hallgato>
  
</hallgatok>
