=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh1/b.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="autok">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="auto" type="autoTipus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="autoTipus">
    <xs:sequence>
      <xs:element name="marka" type="xs:string"/>
      <xs:element name="gyartasi-datum" type="xs:date"/>
      <xs:element name="szin" type="szinTipus" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rendszam" type="rendszamTipus" use="required"/>
  </xs:complexType>
  
  <xs:simpleType name="rendszamTipus">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="szinSimpleTipus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="fehér"/>
      <xs:enumeration value="ezüst"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="szinTipus">
    <xs:simpleContent>
      <xs:extension base="szinSimpleTipus">
        <xs:attribute name="metalozott" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh1/b.xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<autok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="b.xsd">
  
  <auto rendszam="ABC-123">
    <marka>Honda</marka>
    <gyartasi-datum>2013-01-01</gyartasi-datum>
    <szin metalozott="true">fehér</szin>
  </auto>
  
  <auto rendszam="ABC-124">
    <marka>Mercedes</marka>
    <gyartasi-datum>2014-01-01</gyartasi-datum>
    <szin>ezüst</szin>
  </auto>
  
  <auto rendszam="ABC-125">
    <marka>BMW</marka>
    <gyartasi-datum>2014-02-01</gyartasi-datum>
  </auto>
  
</autok>
