=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh3_start_b/data/autok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="autoDB">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="auto" type="autoTipus" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="tulajdonos" type="tulajdonosTipus" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
    
    <xs:key name="rszPK">
      <xs:selector xpath="auto"/>
      <xs:field xpath="@rendszam"/>
    </xs:key>
    
    <xs:key name="idPK">
      <xs:selector xpath="tulajdonos"/>
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:keyref name="tulajdonosFK" refer="idPK">
      <xs:selector xpath="auto"/>
      <xs:field xpath="@tulajdonos"/>
    </xs:keyref>
  </xs:element>
  
  <xs:complexType name="autoTipus">
    <xs:sequence>
      <xs:element name="marka" type="xs:string"/>
      <xs:element name="gyartasi-ev" type="xs:gYear"/>
      <xs:element name="szin" type="szinTipus" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="rendszam" type="rendszamTipus" use="required"/>
    <xs:attribute name="tulajdonos" type="xs:int"/>
  </xs:complexType>
  
  <xs:simpleType name="rendszamTipus">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{3}-\d{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="szinSimpleTipus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="fehér"/>
      <xs:enumeration value="ezüst"/>
      <xs:enumeration value="fekete"/>
      <xs:enumeration value="piros"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="szinTipus">
    <xs:simpleContent>
      <xs:extension base="szinSimpleTipus">
        <xs:attribute name="metalozott" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="tulajdonosTipus">
    <xs:sequence>
      <xs:element name="nev" type="nevTipus"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="nevTipus">
    <xs:sequence>
      <xs:element name="vezeteknev" type="xs:string"/>
      <xs:element name="keresztnev" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== szgabsz91/iit-szg/src/assets-en/courses/xml/zh3_start_b/data/autok.xml
<?xml version="1.0" encoding="UTF-8"?>
<autoDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="autok.xsd">
  
  <auto rendszam="ABC-123">
    <marka>Honda</marka>
    <gyartasi-ev>2013</gyartasi-ev>
    <szin metalozott="true">fehér</szin>
  </auto>
  
  <auto rendszam="ABC-124" tulajdonos="1">
    <marka>Mercedes</marka>
    <gyartasi-ev>2014</gyartasi-ev>
    <szin>ezüst</szin>
  </auto>
  
  <auto rendszam="ABC-125" tulajdonos="1">
    <marka>BMW</marka>
    <gyartasi-ev>2013</gyartasi-ev>
    <szin metalozott="true">fekete</szin>
  </auto>
  
  <auto rendszam="ABC-126" tulajdonos="2">
    <marka>BMW</marka>
    <gyartasi-ev>2014</gyartasi-ev>
  </auto>
  
  <auto rendszam="ABC-127">
    <marka>Ferrari</marka>
    <gyartasi-ev>2014</gyartasi-ev>
    <szin metalozott="true">piros</szin>
  </auto>
  
  <tulajdonos id="1">
    <nev>
      <vezeteknev>Kovács</vezeteknev>
      <keresztnev>Béla</keresztnev>
    </nev>
  </tulajdonos>
  
  <tulajdonos id="2">
    <nev>
      <vezeteknev>Kis</vezeteknev>
      <keresztnev>Elemér</keresztnev>
    </nev>
  </tulajdonos>
  
</autoDB>
